### ISSUE TITLE
where's the tensorrt path?

### ISSUE THREAD

**Issue by YacratesWyh** [SeanWangJS/grid-sample3d-trt-plugin#6]
I installed it in site-packages, and it's split into pieces. 

![image](https://github.com/user-attachments/assets/ebd7167c-5442-4342-8e68-9c138a25d837)
Also in dkpg tutorial it found in /usr/src instead of /usr/local. And there's no include path

**Comment by uyiyiyi** [comment]
Hi! how did you solve this problem?

**Comment by prajwaljpj** [comment]
> Hi! how did you solve this problem?

You need to download tensorrt from the Nvidia repository. Python tensorrt does not have c++ include files.
