### ISSUE TITLE
Excursion of the original torch func.

### ISSUE THREAD

**Issue by YacratesWyh** [SeanWangJS/grid-sample3d-trt-plugin#9]
When testing your provided test python file [test_grid_sample3d.py], I found unstable excursion. 
[12/18/2024-17:51:00] [TRT] [V] CUDA lazy loading is enabled.
max diff: 4.351330921053886%
min diff: -77.00295448303223%
Also test another example with max 11% min -12%.
I've tested onnx opset20 and found only less than 1e-4 :
max diff: 3.547704068296298e-05%
min diff: -3.2013053896662313e-05%
. Any suggestion of how to correct?
====edit====
By changing the example channel from 32 to 4,
    input_shape = (22, 4, 16, 64, 64)
the problem seems that is solved to 
max diff: 3.9723817259073257%
min diff: -4.3887075036764145%.
Maybe it's how it's functioning?

**Comment by SeanWangJS** [comment]
I did see this unstable excursion while using float16 precision. And I found the reason is that the interpolation operation have poor results when the digit precision is low.

**Comment by YacratesWyh** [comment]
Soryy I missed the line when making engine, changing make_network_and_engine is enough though. No need to modify input type to 64 to enable force autotuning to float32.
